### Raiz da aplicação
GET http://localhost:5169/

### Listagem de produtos
GET http://localhost:5169/produtos/listar

### Busca de produtos
GET http://localhost:5169/produtos/buscar/Macarrão

### Cadastro de produtos
POST http://localhost:5169/produtos/cadastrar/Macarrão/alimento/7.50